In [ ]:
import pandas as pd
import numpy as np
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
demo="hello vitt!!! i'm ishita gupta. welcome to the ai session"
demo

"hello vitt!!! i'm ishita gupta. welcome to the ai session"

In [ ]:
#1) remove the special char
#2) converting entire text to upper to lower case
#3) split the data
#4) remove stopwords
#5) stemming/lematiziation
#6) join..&build the model

In [ ]:
#remove special char
reg=re.sub('[^a-zA-Z]',' ',demo)
reg

'hello vitt    i m ishita gupta  welcome to the ai session'

In [ ]:
#2) converting entire text to upper to lower case
lw=reg.lower()
lw

'hello vitt    i m ishita gupta  welcome to the ai session'

In [ ]:
#3) split the data
sp=lw.split()
sp

['hello',
 'vitt',
 'i',
 'm',
 'ishita',
 'gupta',
 'welcome',
 'to',
 'the',
 'ai',
 'session']

In [ ]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
#4) remove stopwords
sw=[word for word in sp if word not in set(stopwords.words('english'))]
sw

['hello', 'vitt', 'ishita', 'gupta', 'welcome', 'ai', 'session']

In [ ]:
#5) stemming/lematiziation
ps=PorterStemmer()
p=[ps.stem(word) for word in sw]
p

['hello', 'vitt', 'ishita', 'gupta', 'welcom', 'ai', 'session']

In [ ]:
#joining the words
jt=' '.join(p)
jt

'hello vitt ishita gupta welcom ai session'

In [ ]:
# convert text to number
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer()
cv.fit_transform([jt]).toarray()

array([[1, 1, 1, 1, 1, 1, 1]])

In [ ]:
df=pd.read_csv('/content/Restaurant_Reviews.tsv',delimiter='\t')
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [ ]:
data=[]
for i in range(1000):
           review=df['Review'][i]
           review=re.sub('[^a-zA-Z]','',review)
           review=review.lower()
           review=review.split()
           review=[ps.stem(word) for word in review if word not in set(stopwords.words('english'))]
           review=' '.join(review)
           data.append(review)


In [ ]:
data

['wowlovedthisplac',
 'crustisnotgood',
 'nottastyandthetexturewasjustnasti',
 'stoppedbyduringthelatemaybankholidayoffricksteverecommendationandlovedit',
 'theselectiononthemenuwasgreatandsowerethepric',
 'nowiamgettingangryandiwantmydamnpho',
 'honesltyitdidnttastethatfresh',
 'thepotatoeswerelikerubberandyoucouldtelltheyhadbeenmadeupaheadoftimebeingkeptunderawarm',
 'thefriesweregreattoo',
 'agreattouch',
 'servicewasveryprompt',
 'wouldnotgoback',
 'thecashierhadnocarewhatsoeveronwhatihadtosayitstillendedupbeingwayyyoverpr',
 'itriedthecapecodravolichickenwithcranberrymmmm',
 'iwasdisgustedbecauseiwasprettysurethatwashumanhair',
 'iwasshockedbecausenosignsindicatecashonli',
 'highlyrecommend',
 'waitresswasalittleslowinservic',
 'thisplaceisnotworthyourtimeletalonevega',
 'didnotlikeatal',
 'theburrittosblah',
 'thefoodamaz',
 'serviceisalsocut',
 'icouldcarelesstheinteriorisjustbeauti',
 'sotheyperform',
 'thatsrighttheredvelvetcakeohhhthisstuffissogood',
 'theyneverbroughtasaladw

In [ ]:
x=cv.fit_transform(data).toarray()
#convert to number
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y=df['Liked'].values
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [ ]:
#ann model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential()
model.add(Dense(2000,activation='relu'))
model.add(Dense(3000,activation='relu'))
model.add(Dense(1500,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(x,y,epochs=32)

Epoch 1/32
32/32 [==============================] - 8s 170ms/step - loss: 0.6978 - accuracy: 0.5080
Epoch 2/32
32/32 [==============================] - 6s 185ms/step - loss: 0.3401 - accuracy: 0.8820
Epoch 3/32
32/32 [==============================] - 6s 179ms/step - loss: 0.0018 - accuracy: 0.9990
Epoch 4/32
32/32 [==============================] - 6s 173ms/step - loss: 2.0528e-05 - accuracy: 1.0000
Epoch 5/32
32/32 [==============================] - 6s 197ms/step - loss: 3.3394e-08 - accuracy: 1.0000
Epoch 6/32
32/32 [==============================] - 5s 168ms/step - loss: 2.8971e-08 - accuracy: 1.0000
Epoch 7/32
32/32 [==============================] - 6s 202ms/step - loss: 2.5950e-08 - accuracy: 1.0000
Epoch 8/32
32/32 [==============================] - 5s 169ms/step - loss: 2.4462e-08 - accuracy: 1.0000
Epoch 9/32
32/32 [==============================] - 7s 204ms/step - loss: 2.3008e-08 - accuracy: 1.0000
Epoch 10/32
32/32 [==============================] - 6s 177ms/step - loss: 2

In [ ]:
#test
test='good food...love it'
print(test)
print('#'*20)
test=re.sub('[^a-zA-Z]',' ',test)
print(test)
print('#'*20)
test=test.lower()
print(test)
print('#'*20)
test=test.split()
print(test)
print('#'*20)
test = [ps.stem(word) for word in test if word not in set(stopwords.words('english'))]
print(test)
print('#'*20)
test = ' '.join(test)
print(test)
print('#'*20)
test=cv.transform([test]).toarray()
print(test)
print('#'*20)
pred=model.predict(test)
print(pred)
print('#',20)
if(pred>0.5):
   print('positive')
else:
    print('negative')

good food...love it
####################
good food   love it
####################
good food   love it
####################
['good', 'food', 'love', 'it']
####################
['good', 'food', 'love']
####################
good food love
####################
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0

In [ ]:
test = 'Worst food...hate it'
print(test)
print('#'*20)
test = re.sub('[^a-zA-Z]',' ',test)
print(test)
print('#'*20)
test = test.lower()
print(test)
print('#'*20)
test = test.split()
print(test)
print('#'*20)
test = [ps.stem(word) for word in test if word not in set(stopwords.words('english'))]
print(test)
print('#'*20)
test = ' '.join(test)
print(test)
print('#'*20)
test = cv.transform([test]).toarray()
print(test)
print('#'*20)
pred = model.predict(test)
print(pred)
print('#'*20)
if pred>0.5:
  print('positive')
else:
  print('negative')

Worst food...hate it
####################
Worst food   hate it
####################
worst food   hate it
####################
['worst', 'food', 'hate', 'it']
####################
['worst', 'food', 'hate']
####################
worst food hate
####################
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0